spring.application.name=cooker
spring.data.mongodb.database=cooker
spring.data.mongodb.uri=mongodb://localhost:27017/cooker
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# JWT Configuration
app.jwt.secret=I&Si$9jys8#%8TZH%&tC2gHpPIt^NG6A
app.jwt.expiration=86400000

# Data Seeder Configuration
app.seeder.enabled=false

# Allow null for primitives during deserialization (disable failure)
spring.jackson.deserialization.fail-on-null-for-primitives=false