---
config:
    mirrorActors: false
---

sequenceDiagram
    actor U as Usuário
    participant F as Frontend
    participant C as AuthController
    participant S as AuthService
    participant R as UserRepository
    participant A as AuthenticationManager

    U->>+F: Criar conta
    F->>+C: POST /api/auth/register {RegisterRequest}
    C->>+S: register(RegisterRequest registerRequest)

    S->>+R: findByEmail(String email)
    R-->>-S: User
    break Email existe
        S-->>C: Exception
        C-->>F: HTTP 412
        F-->>U: Email já cadastrado
    end

    S->>+R: findByHandle(String handle)
    R-->>-S: User
    break Nome de usuário existe
        S-->>C: Exception
        C-->>F: HTTP 412
        F-->>U: Nome de usuário já cadastrado
    end

    S->>+A: authenticate(String email, String password)
    A-->>-S: Authentication
    S-->>-C: AuthResponse
    C-->>-F: HTTP 200
    F-->>-U: Usuário criado